# Generated by Django 5.2.8 on 2025-12-15 06:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год')),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Квартал')),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('is_closed', models.BooleanField(default=False, help_text='Запрет на редактирование данных после закрытия периода', verbose_name='Период закрыт')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'ordering': ['-year', '-quarter', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text="Бюджет 2025, Rolling Forecast Dec'25 и т.д.", max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('actual', 'Факт'), ('budget', 'Бюджет'), ('forecast', 'Прогноз'), ('adjustment', 'Корректировка'), ('plan', 'План')], max_length=20, verbose_name='Тип сценария')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('base_scenario', models.ForeignKey(blank=True, help_text='Для корректировок и новых версий', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.scenario', verbose_name='Базируется на')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
                ('end_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_ends', to='core.timeperiod', verbose_name='Конечный период')),
                ('start_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_starts', to='core.timeperiod', verbose_name='Начальный период')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timeperiod',
            index=models.Index(fields=['company', 'year', 'quarter', 'month'], name='core_timepe_company_7d4a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='timeperiod',
            index=models.Index(fields=['is_closed'], name='core_timepe_is_clos_e18dc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeperiod',
            unique_together={('company', 'year', 'quarter', 'month')},
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['company', 'type', 'is_active'], name='core_scenar_company_1ac5da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together={('company', 'name', 'version')},
        ),
    ]
