# Generated by Django 5.2.8 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['company', 'slug'], name='core_scenar_company_1b4ad5_idx'),
        ),
    ]
