# Generated by Django 5.2.8 on 2025-12-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('dimensions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, help_text='В основной валюте компании', max_digits=19, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(blank=True, help_text='Ручной ввод, Excel, ERP и т.д.)', max_length=100, verbose_name='Источник')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.chartofaccounts', verbose_name='Счет плана счетов')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_lines', to='dimensions.budgetarticle', verbose_name='Статья бюджета')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.costcenter', verbose_name='ЦФО')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.department', verbose_name='Подразделение')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_lines', to='core.timeperiod', verbose_name='Период')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.project', verbose_name='Проект')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_lines', to='core.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Строка финансовых данных',
                'verbose_name_plural': 'Финансовые данные',
                'ordering': ['-period__year', '-period__month', 'article__code'],
                'indexes': [models.Index(fields=['company', 'scenario', 'period'], name='financials__company_873ef6_idx'), models.Index(fields=['article'], name='financials__article_e4b472_idx'), models.Index(fields=['cost_center'], name='financials__cost_ce_205c07_idx'), models.Index(fields=['project'], name='financials__project_1503e9_idx'), models.Index(fields=['department'], name='financials__departm_c2f47a_idx')],
                'unique_together': {('scenario', 'period', 'article', 'cost_center', 'department', 'project', 'account')},
            },
        ),
    ]
