# Generated by Django 5.2.8 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_scenario_core_scenar_company_1b4ad5_idx'),
        ('dimensions', '0002_department_created_at_department_updated_at_and_more'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='financialline',
            name='financials__article_e4b472_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialline',
            name='financials__cost_ce_205c07_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialline',
            name='financials__project_1503e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='financialline',
            name='financials__departm_c2f47a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='financialline',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['company', 'article'], name='financials__company_2314d5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['company', 'cost_center'], name='financials__company_d278eb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['company', 'project'], name='financials__company_ab1522_idx'),
        ),
        migrations.AddIndex(
            model_name='financialline',
            index=models.Index(fields=['company', 'department'], name='financials__company_199dd8_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialline',
            constraint=models.UniqueConstraint(fields=('company', 'scenario', 'period', 'article', 'cost_center', 'department', 'project', 'account'), name='unique_financial_line_with_nulls', nulls_distinct=True),
        ),
    ]
