# Generated by Django 5.2.8 on 2026-01-13 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_scenario_core_scenar_company_1b4ad5_idx'),
        ('dimensions', '0002_department_created_at_department_updated_at_and_more'),
        ('financials', '0002_remove_financialline_financials__article_e4b472_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheetMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=255, verbose_name='Строка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sign', models.IntegerField(choices=[(1, '+'), (-1, '-')], default=1, verbose_name='Знак')),
                ('line_code', models.CharField(blank=True, max_length=20, verbose_name='Код строки')),
                ('section', models.CharField(choices=[('NON_CURRENT_ASSETS', 'Внеоборотные активы'), ('CURRENT_ASSETS', 'Оборотные активы'), ('EQUITY', 'Капитал'), ('LONG_TERM_LIABILITIES', 'Долгосрочные обязательства'), ('SHORT_TERM_LIABILITIES', 'Краткосрочные обязательства')], max_length=50, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Маппинг строки баланса',
                'verbose_name_plural': 'Маппинги баланса',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=255, verbose_name='Строка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sign', models.IntegerField(choices=[(1, '+'), (-1, '-')], default=1, verbose_name='Знак')),
                ('section', models.CharField(choices=[('OPERATING', 'Операционная деятельность'), ('INVESTING', 'Инвестиционная деятельность'), ('FINANCING', 'Финансовая деятельность')], max_length=50, verbose_name='Раздел')),
                ('method', models.CharField(choices=[('DIRECT', 'Прямой'), ('INDIRECT', 'Косвенный')], default='DIRECT', max_length=20, verbose_name='Метод')),
            ],
            options={
                'verbose_name': 'Маппинг строки ДДС',
                'verbose_name_plural': 'Маппинги ДДС',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ConsolidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('FULL', 'Полная элиминация'), ('PROPORTIONAL', 'Пропорциональная (по доле владения)'), ('REVENUE_EXPENSE', 'Только доходы/расходы'), ('BALANCE_ONLY', 'Только балансовые статьи')], default='FULL', max_length=20, verbose_name='Метод элиминации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('description', models.TextField(blank=True, verbose_name='Описание правила')),
            ],
            options={
                'verbose_name': 'Правило консолидационной элиминации',
                'verbose_name_plural': 'Правила консолидационной элиминации',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('base_currency', models.CharField(max_length=3, verbose_name='Базовая валюта')),
                ('target_currency', models.CharField(max_length=3, verbose_name='Целевая валюта')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Курс')),
                ('source', models.CharField(blank=True, default='', max_length=50, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('section', models.CharField(blank=True, help_text='NON_CURRENT_ASSETS, REVENUE, OPEX и т.д.', max_length=50, verbose_name='Раздел отчёта')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Агрегат финансовых данных',
                'verbose_name_plural': 'Агрегаты финансовых данных',
            },
        ),
        migrations.CreateModel(
            name='FinancialLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Блокировка периода',
                'verbose_name_plural': 'Блокировки периодов',
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код метрики')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('formula', models.TextField(help_text='Например: SUM(REVENUE) - SUM(COGS) или сложные выражения', verbose_name='Формула')),
                ('formula_type', models.CharField(choices=[('SIMPLE', 'Простая арифметика'), ('RATIO', 'Коэффициент'), ('CUSTOM', 'Пользовательская логика')], default='SIMPLE', max_length=20, verbose_name='Тип формулы')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Определение метрики',
                'verbose_name_plural': 'Определения метрик',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Значение')),
                ('calculation_details', models.JSONField(blank=True, null=True, verbose_name='Детали расчёта')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Рассчитано')),
            ],
            options={
                'verbose_name': 'Значение метрики',
                'verbose_name_plural': 'Значения метрик',
            },
        ),
        migrations.CreateModel(
            name='ProfitLossMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=255, verbose_name='Строка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('sign', models.IntegerField(choices=[(1, '+'), (-1, '-')], default=1, verbose_name='Знак')),
            ],
            options={
                'verbose_name': 'Маппинг строки P&L',
                'verbose_name_plural': 'Маппинги P&L',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='financialline',
            options={'ordering': ['-period__year', '-period__month', 'article__code'], 'verbose_name': 'Строка финансовых данных', 'verbose_name_plural': 'Строки финансовых данных'},
        ),
        migrations.RemoveConstraint(
            model_name='financialline',
            name='unique_financial_line_with_nulls',
        ),
        migrations.AlterField(
            model_name='financialline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.chartofaccounts'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensions.budgetarticle', verbose_name='Статья бюджета'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.costcenter'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.department'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.timeperiod'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dimensions.project'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.scenario'),
        ),
        migrations.AlterField(
            model_name='financialline',
            name='source',
            field=models.CharField(blank=True, help_text='Ручной ввод, Excel, ERP, интеграция и т.д.', max_length=100, verbose_name='Источник'),
        ),
        migrations.AlterUniqueTogether(
            name='financialline',
            unique_together={('company', 'scenario', 'period', 'article', 'cost_center', 'department', 'project', 'account')},
        ),
        migrations.AddField(
            model_name='balancesheetmapping',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimensions.budgetarticle'),
        ),
        migrations.AddField(
            model_name='cashflowmapping',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimensions.budgetarticle'),
        ),
        migrations.AddField(
            model_name='consolidationrule',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dimensions.budgetarticle', verbose_name='Статья бюджета'),
        ),
        migrations.AddField(
            model_name='consolidationrule',
            name='company_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elimination_rules_out', to='accounts.company', verbose_name='Компания-продавец'),
        ),
        migrations.AddField(
            model_name='consolidationrule',
            name='company_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elimination_rules_in', to='accounts.company', verbose_name='Компания-покупатель'),
        ),
        migrations.AddIndex(
            model_name='currencyrate',
            index=models.Index(fields=['date', 'base_currency', 'target_currency'], name='financials__date_e6da4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyrate',
            unique_together={('date', 'base_currency', 'target_currency', 'source')},
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimensions.budgetarticle', verbose_name='Статья (или группа)'),
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimensions.costcenter'),
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.timeperiod'),
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimensions.project'),
        ),
        migrations.AddField(
            model_name='financialaggregate',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.scenario'),
        ),
        migrations.AddField(
            model_name='financiallock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='financiallock',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financiallock',
            name='period_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks_from', to='core.timeperiod'),
        ),
        migrations.AddField(
            model_name='financiallock',
            name='period_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locks_to', to='core.timeperiod'),
        ),
        migrations.AddField(
            model_name='financiallock',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.scenario'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рассчитал'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='financials.metricdefinition'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.timeperiod'),
        ),
        migrations.AddField(
            model_name='metricvalue',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.scenario'),
        ),
        migrations.AddField(
            model_name='profitlossmapping',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimensions.budgetarticle'),
        ),
        migrations.AlterUniqueTogether(
            name='balancesheetmapping',
            unique_together={('article', 'line_name')},
        ),
        migrations.AlterUniqueTogether(
            name='consolidationrule',
            unique_together={('article', 'company_from', 'company_to')},
        ),
        migrations.AddIndex(
            model_name='financialaggregate',
            index=models.Index(fields=['company', 'scenario', 'period', 'section'], name='financials__company_b78fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaggregate',
            index=models.Index(fields=['company', 'scenario', 'period', 'article'], name='financials__company_12622d_idx'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['company', 'scenario', 'period'], name='financials__company_059621_idx'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['definition'], name='financials__definit_03bb9b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together={('company', 'definition', 'scenario', 'period')},
        ),
    ]
