# Generated by Django 5.2.8 on 2026-01-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_balancesheetmapping_cashflowmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialline',
            name='slug',
            field=models.SlugField(blank=True, help_text='Уникальный идентификатор для URL', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
