# Generated by Django 5.2.8 on 2026-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_scenario_core_scenar_company_1b4ad5_idx'),
        ('dimensions', '0002_department_created_at_department_updated_at_and_more'),
        ('financials', '0004_financialline_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialline',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='financialline',
            constraint=models.UniqueConstraint(fields=('company', 'scenario', 'period', 'article', 'cost_center', 'department', 'project', 'account'), name='unique_financial_line', nulls_distinct=True),
        ),
    ]
