# Generated by Django 5.2.8 on 2025-12-18 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_scenario_core_scenar_company_1b4ad5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=10, verbose_name='Тип файла')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обработка'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Всего строк')),
                ('rows_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано')),
                ('rows_success', models.PositiveIntegerField(default=0, verbose_name='Успешно')),
                ('rows_failed', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.scenario', verbose_name='Сценарий')),
            ],
            options={
                'verbose_name': 'Задача импорта',
                'verbose_name_plural': 'Задачи импорта',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'slug'], name='data_ingest_company_c11dee_idx')],
                'unique_together': {('company', 'slug')},
            },
        ),
    ]
