# Generated by Django 5.2.8 on 2025-12-23 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_scenario_core_scenar_company_1b4ad5_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, verbose_name='Slug')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('report_type', models.CharField(choices=[('pnl', 'P&L / Отчёт о прибылях и убытках'), ('balance', 'Баланс'), ('cashflow', 'Cash Flow'), ('plan_fact', 'План-Факт анализ'), ('custom', 'Пользовательский')], max_length=50, verbose_name='Тип отчёта')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Шаблон отчёта',
                'verbose_name_plural': 'Шаблоны отчётов',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчёта')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Файл отчёта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('generating', 'Генерируется'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('end_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_ends', to='core.timeperiod')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.scenario')),
                ('start_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_starts', to='core.timeperiod')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reports.reporttemplate')),
            ],
            options={
                'verbose_name': 'Сгенерированный отчёт',
                'verbose_name_plural': 'Сгенерированные отчёты',
                'ordering': ['-created_at'],
            },
        ),
    ]
