# Generated by Django 5.2.8 on 2025-12-15 06:24

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(help_text='Полное или краткое наименование компании', max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, help_text='ИНН компании (10 или 12 символов)', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('currency_default', models.CharField(default='RUB', help_text='ISO-код валюты по умолчанию (RUB, USD, EUR и т.д.)', max_length=3, verbose_name='Основная валюта')),
                ('fiscal_year_start', models.DateField(default=accounts.models.fiscal_year_start_default, help_text='Дата начала финансового года (обычно 1 января)', verbose_name='Начало финансового года')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Если False — компания архивирована, доступ запрещён', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='accounts_co_name_a6c199_idx'), models.Index(fields=['inn'], name='accounts_co_inn_2c8aaa_idx'), models.Index(fields=['is_active'], name='accounts_co_is_acti_4abc2f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор компании'), ('finance', 'Финансист'), ('analyst', 'Аналитик'), ('viewer', 'Просмотр')], default='viewer', max_length=50, verbose_name='Роль')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Роль пользователя в компании',
                'verbose_name_plural': 'Роли пользователей в компаниях',
                'unique_together': {('user', 'company')},
            },
        ),
    ]
